server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: gourav-portfolio-backend
  
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/portfolio_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:${SPRING_DATASOURCE_USERNAME:root}}
    password: ${DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD:Sonu@12345}}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: never
      continue-on-error: true
        
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:gouravkrsah78@gmail.com}
    password: ${EMAIL_PASSWORD:yhicdjngxrfplifa}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        
  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    com.gouravkumar.portfolio: DEBUG
    org.springframework.web: INFO
    org.springframework.mail: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
