server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: gourav-portfolio-backend
  
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/portfolio_db}
    username: ${MYSQLUSER:${MYSQL_USER:${DB_USERNAME:root}}}
    password: ${MYSQLPASSWORD:${MYSQL_PASSWORD:${DB_PASSWORD:mOkjnEREKotplfjKaWcgPspBuTOEcMON}}}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: never
      continue-on-error: true
        
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:gouravkrsah78@gmail.com}
    password: ${EMAIL_PASSWORD:yhicdjngxrfplifa}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    com.gouravkumar.portfolio: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.boot.context.config: DEBUG
    org.springframework.mail: DEBUG
    org.springframework.boot.autoconfigure.mail: DEBUG
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
